### PR TITLE
remove filtering of common strains during loading

### PR DESCRIPTION
**Pull request by CunliangGeng**
The loading part should return all relevant strains to scoring part. And then users should do the filtering of strains in the scoring part. So removing the method `_filter_only_common_strains` from loading process. 

The upcoming PRs will add the filtering of common strains in the scoring part.

### CODE REVIEW

**Comment by CunliangGeng** [comment]
Current dependencies on/for this PR:
* `dev`
  * **PR #178** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/178?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #181** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/181?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #182** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/182?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #183** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/183?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #184** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #185** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/185?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #186** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #187** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/187?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #188** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/188?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #189** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/189?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #190** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/190?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #191** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #192** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/192?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #193** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/193?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #194** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/194?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #196** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/196?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                  * **PR #197** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/197?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                    * **PR #198** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                      * **PR #199** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                        * **PR #200** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/200?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                                          * **PR #201** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/201?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                            * **PR #202** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/202?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #195** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/195?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/200?utm_source=stack-comment).

**Comment by CunliangGeng** [comment]
Current dependencies on/for this PR:
* dev
  * **PR #178** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/178?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #181** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/181?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #182** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/182?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #183** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/183?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #184** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #185** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/185?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #186** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/186?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #187** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/187?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                  * **PR #188** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/188?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                    * **PR #189** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/189?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                      * **PR #190** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/190?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                        * **PR #191** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                          * **PR #192** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/192?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                            * **PR #193** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/193?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                              * **PR #194** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/194?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                * **PR #196** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/196?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                  * **PR #197** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/197?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                    * **PR #198** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                      * **PR #199** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                                        * **PR #200** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/200?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
                                * **PR #195** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/195?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/200?utm_source=stack-comment).

**Review by gcroci2 — COMMENTED** [review]
Maybe I'm missing something here, but if a strain is not relevant (i.e., it's not present in both genomic and metabolomic data), what is the use case in which it could be used for the scoring part anyway? Which means, how can a link be present (and scored) at all in such cases?

**Comment by justinjjvanderhooft** [comment]
Good point @gcroci2, I think it depends on how we organize the loading of the strains - and the matching. This is one of the most critical steps as so far, most of the issues arise from this. @CunliangGeng, what is your current idea? First load everything and then ensure there are matches in a second step, before moving on to the scoring?

**Comment by CunliangGeng** [comment]
@gcroci2 @justinjjvanderhooft  If a strain is not a common strain, it could be used by only genomics or only metabolomics or neither. The current workflow will load everything and pass them to scoring part, users then set what strains to use in the scoring part, e.g. there would be a parameter in scoring like `use_only_common_strains` and/or `filter_specified_strains`...

**Comment by justinjjvanderhooft** [comment]
@CunliangGeng I think I can follow your logic, as in, we load all that is there, and then prior to scoring we let the user choose/assess what will be considered....is that how you envisioned it? I think what @gcroci2 and myself are referring to is that, for any "linking score" to work, we need at least 1 (and preferably more!) "common" strains between the genome and metabolome data that is uploaded. For the PoDP data, this is not an issue, as they are matched through the PoDP metadata. For the local data (where many users will start with), what do we currently have in mind? Upon preparing the data, do a validation that at least one strain label is matching (common) between the genome and metabolome data? And/or give an overview of common and "not-matching" strains (labels) prior to calculating the score(s). It is good that you raise this point. I am happy to follow your advice/logic @CunliangGeng, as long as it is clear to the user in an early stage how many matching (common) strains there are available for any scoring. Whilst it is still unclear to me now what we can do with the not matching strain labels, I can think of enough use cases (i.e., streamlined loading of genome data for networking, etc.) - is that what you had in mind @CunliangGeng?

**Comment by CunliangGeng** [comment]
@justinjjvanderhooft @gcroci2 
Here are my answers to Justin's questions:

If users set it to use common strains for scoring and actually there is no common strains, then it should raise an warning/error.

We can provide methods in class `NPLinker` to check if common strains exist or not, or to check the number of common/non-common strains.

> For the local data (where many users will start with), what do we currently have in mind? Upon preparing the data, do a validation that at least one strain label is matching (common) between the genome and metabolome data?

For the local data mode, users have to manually prepare the strain mappings and ensure the strain id has alias for both genomics and metabolomics data. After loading the strain mappings (and also other data), users can use the new method in `NPLinker` class to check the number of different types of strains.

> Whilst it is still unclear to me now what we can do with the not matching strain labels, I can think of enough use cases (i.e., streamlined loading of genome data for networking, etc.) - is that what you had in mind 

For the data like BGC that do not have a matched strain, they won't be passed to scoring stage. In the loading stage, the number of matched/unmatched data will be reported in the log.

**Comment by justinjjvanderhooft** [comment]
Thanks for your answers @gcroci2! I think it may also be a "semantic" confusion, but I think I can follow the logic now. Let's get back to this in an online / in person meeting to clarify everything :-)

**Comment by CunliangGeng** [comment]
@gcroci2 Please explicitly approve the PR if it looks good. Without approval from at least one reviewer, the PR cannot be merged :-)

**Review by gcroci2 — APPROVED** [review]

**Comment by CunliangGeng** [comment]
### Merge activity

* **Jan 24, 10:20 AM**: @CunliangGeng started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/200).
* **Jan 24, 10:28 AM**: [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/200) rebased this pull request as part of a merge.
* **Jan 24, 10:29 AM**: @CunliangGeng merged this pull request with [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/200).

**Pull request merged**
