### PR TITLE
setup docs with Mkdocs

### PR DESCRIPTION
**Pull request by CunliangGeng**
[MkDocs](https://www.mkdocs.org/) is going to be used to build doc website.  So that we can use markdown instead of [rst](https://docutils.sourceforge.io/rst.html) to write tutorials and docs. 

Major changes
- Remove old setup of docs that depends on Sphinx
- Add new setup of docs using MkDocs

### CODE REVIEW

**Comment by CunliangGeng** [comment]
* **#218** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/218?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#217** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/217?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#214** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#212** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/212?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#211** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/211?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#210** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/210?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#209** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/209?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#208** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/208?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CunliangGeng and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gcroci2 — APPROVED** [review]
Nice template on the website! I just wonder, why Mkdocs instead of Sphinx? .md files can be used with Sphinx as well (see for example [in deeprank2](https://github.com/DeepRank/deeprank2/tree/main/docs))

**Comment by CunliangGeng** [comment]
Yep, Sphinx can support markdown with the help of [myst_parser](https://myst-parser.readthedocs.io/en/latest/). Markdown support is only a minor reason I choose mkdocs. 
The major ones are that (1) I got tired of Sphnix after using it for years (2) Mkdocs has simpler setup and more fancy and  modern looking (with the theme [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)) than Sphinx :-)

**Comment by CunliangGeng** [comment]
### Merge activity

* **Mar 5, 10:38 AM EST**: @CunliangGeng started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/218).
* **Mar 5, 10:44 AM EST**: [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/218) rebased this pull request as part of a merge.
* **Mar 5, 10:45 AM EST**: @CunliangGeng merged this pull request with [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/218).

**Pull request merged**
