### PR TITLE
refactor: move non-download functionalities out of `PODPDownloader` - `_run_bigscape`

### LINKED ISSUE #121: Refactor `Downloader` class to have a specific PoDP downloader
Right now, `src/nplinker/pairedomics/downloader.py` contains the Downloader class which is basically a PoDP downloader, and not a general one. 

- [x] rename class `Downloader` to `PODPDownloader`

Extract download code for different data source to independent modules
- [x] #127  
- [x] #138 

Move non-download functionalities out of `PODPDownloader`
- [x]  #143 

The downloading is handled by class `DatasetArranger`
 - [x] #215

### PR DESCRIPTION
**Pull request by gcroci2**
- `_run_bigscape` method has been moved to src/nplinker/pairedomics/runbigscape.py as a function and it is now called `podp_run_bigscape`
- src/nplinker/pairedomics/downloader.py now uses `podp_run_bigscape`
- Type hints in src/nplinker/pairedomics/runbigscape.py have been added

### CODE REVIEW

**Comment by gcroci2** [comment]
In src/nplinker/pairedomics/runbigscape.py, `run_bigscape` takes as input `extra_params`, which to me appears to be a string. But then in the `if __name__ == "__main__":` statement, `cutoffs=[0.3]` is passed as `extra_params` parameter. Prospector indeed classifies it as an error, because it doesn't expect a `cutoffs` parameter.

**Comment by CunliangGeng** [comment]
> In src/nplinker/pairedomics/runbigscape.py, `run_bigscape` takes as input `extra_params`, which to me appears to be a string. But then in the `if __name__ == "__main__":` statement, `cutoffs=[0.3]` is passed as `extra_params` parameter. Prospector indeed classifies it as an error, because it doesn't expect a `cutoffs` parameter.

Indeed, the `extra_params` is a string with space as separator.

**Review by CunliangGeng — APPROVED** [review]
Ideally the download and run logics should be independent. To move run_bigscape out of PODPDownloader, we have to move the run logics to a higher level (i.e. to loader.py). Let's keep it as it is and really move it out when refactoring the loader part.

**Comment by gcroci2** [comment]
> Ideally the download and run logics should be independent. To move run_bigscape out of PODPDownloader, we have to move the run logics to a higher level (i.e. to loader.py). Let's keep it as it is and really move it out when refactoring the loader part.

Sounds good, I mentioned it in the `DataLoader` issue #145

**Pull request merged**
