### PR TITLE
Allow bigscape run for local mode

### PR DESCRIPTION
**Pull request by CunliangGeng**
This PR enables the support of running bigscape in local mode when users does not provide bigscape data. If users provide data, then only validate it.

### CODE REVIEW

**Comment by CunliangGeng** [comment]
* **#277** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/277?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#276** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/276?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#275** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/275?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @CunliangGeng and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gcroci2 — APPROVED** [review]

**Comment by gcroci2** [comment]
Tests are failing though @CunliangGeng:

```bash
FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_genbank_id - ValueError: No antiSMASH data found for any genome
FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_jgi_id - ValueError: No antiSMASH data found for any genome
FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_genbank_jgi_id - ValueError: No antiSMASH data found for any genome
```

**Comment by CunliangGeng** [comment]
> Tests are failing though @CunliangGeng:
> 
> ```shell
> FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_genbank_id - ValueError: No antiSMASH data found for any genome
> FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_jgi_id - ValueError: No antiSMASH data found for any genome
> FAILED tests/unit/genomics/test_podp_antismash_downloader.py::test_genbank_jgi_id - ValueError: No antiSMASH data found for any genome
> ```

Yes, it's a bit annoying to test online data, very easy to fail due to the change of the website. Let's ignore these failed tests at the moment,

**Comment by CunliangGeng** [comment]
### Merge activity

* **Sep 17, 8:12 AM EDT**: @CunliangGeng started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/277).
* **Sep 17, 8:18 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/277) rebased this pull request as part of a merge.
* **Sep 17, 8:19 AM EDT**: @CunliangGeng merged this pull request with [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/277).

**Pull request merged**
