### PR TITLE
NPClassScore scoring

### PR DESCRIPTION
**Pull request by louwenjjr**
Hi Andrew!

I finally implemented the linking score based on chemical class matching, which we decided to call NPClassScore. You can read about using NPClassScore to filter the proposed link lists after Metcalf scoring within the Crusemann data in our preprint here: https://www.researchsquare.com/article/rs-1391827/.

I implemented it as an additional scoring method as you initially suggested, named 'NPClassScoring'. In my tests it now runs succesfully and not including any chemical class information should not affect any other aspects of NPLinker. Let me know if it runs for you, and if you have comments!

If NPClassScoring is attempted when there are no chemical class predictions loaded it should throw this error:
```
12:04:58 [WARNING] methods.py:950, There are no methods available! This is probably because no class predictions (canopus, etc.) were present or they are not loaded correctly
Traceback (most recent call last):
File "nplinker_test_podp.py", line 18, in <module>
npcl = npl.scoring_method('npclassscore')
File "/home/louwe015/NPLinker/nplinker/prototype/nplinker/nplinker.py", line 565, in scoring_method
return self._scoring_methods.get(name, None)(self)
File "/home/louwe015/NPLinker/nplinker/prototype/nplinker/scoring/methods.py", line 687, in __init__
self.method = self.method_options[0]
IndexError: list index out of range
```

The various changed sections:
- methods.py: NPClassScoring class for performing the NPClassScore. It can create a score between all objects from the genome and metabolome (so also bgc <-> spectra/MFs). I tried to be flexible with what can be object and target. The most important function is _npclass_score: the function that actually does the scoring based on one obj and one target.
- I created a new folder class_info in which there are three new python files:
     1. class_matches.py: Contains ClassMatches that reads the MIBiG info with chemical classes and stores the class-matching tables. The MIBiG file is stored here: prototype/nplinker/data/MIBiG2.0_compounds_with_AS_BGC_CF_NPC_classes.txt. The class_matches tables are nested dicts with a pd.DataFrame at the end so accessing the scores is quite easy. This is maybe not the fastest though, if you have any suggestions for this please let me know.
     4. chem_classes.py: Holds the classes for reading and storing the chemical class predictions. ChemClassPredictions that loads CanopusResults and MolNetEnhancerResults, and is added to npl as chem_classes. It is good to note that CANOPUS predictions are only processed correctly with canopus_treemap when the GNPS MN version is SNETS-V2, If that isn't the case the output from canopus is loaded directly but only for spectra so far. I'm still working on this further, but when you test it take this into account. MolNetEnhancer results should be downloaded from GNPS and stored in a dir called root/molnetenhancer.
     5. runcanopus.py: Runs CANOPUS in a similar fashion to runbigscape.py
     6. I added some basic tests for class_matches.py and chem_classes.py
- loader.py: Added a _load_class_info function to load everything related to classes. New global variables for canopus and molnetenhancer. For now CANOPUS is not run by default.
- nplinker.py: Added new scoring method NPClassScoring.NAME: NPClassScoring. chem_classes and class_matches are taken from ._loader.
- Dockerfile.base - I tried to reflect the changes to download sirius and install canopus_treemap in the conda env
- I added some notebooks to notebooks/npclassscore_linking. Also the Crusemann strain mappings file that I used and reference to in the paper is there: crusemann_strain_mappings.csv

### CODE REVIEW

**Comment by andrewramsay** [comment]
Hi Joris, thanks for the nice summary there, I hadn't been keeping up with all your commits. That all sounds good to me! I'll try to find some time to run your branch tomorrow and see if I run into any problems, happy to merge the PR as soon as I've done that.

**Comment by louwenjjr** [comment]
Thanks Andrew! Sounds good, I'll make those changes!

>When I try to run the newly built Docker image (with Canopus disabled as per the default) it throws an exception on the line from canopus.classifications_to_gnps import analyse_canopus in class_info/chem_classes.py. I thought it might be a typo for runcanopus vs canopus but it doesn't seem to be, I can't find "analyse_canopus" anywhere in the codebase. Maybe a module is missing from the set of committed files?

So this is from the canopus_treemap package that should also be installed in the Dockerfile.base:
```# install canopus_treemap to convert canopus output
git clone https://github.com/louwenjjr/canopus_treemap.git && \
pip install -e canopus_treemap && \
rm -rf canopus_treemap && \
```
Could you maybe check if this is correctly installed?

**Comment by andrewramsay** [comment]
Ah I missed that, I'll check after the meeting!

**Comment by andrewramsay** [comment]
It looks like when you run pip install in that particular form it doesn't actually copy the source files anywhere, it just inserts the directory into the PYTHONPATH. If I remove the "rm -rf" line then it imports that module without any trouble.

I tried loading a dataset with "run_canopus = false" and that seemed to go as normal. Then I tried again with "run_canopus = true" and there were a bunch of "WARNING ..." messages displayed as it started up but it doesn't seem to have run into anything critical. It's still running Sirius at the moment, I guess that normally takes a while?

Will have a look at your notebooks tomorrow!

**Comment by andrewramsay** [comment]
> Then I tried again with "run_canopus = true" and there were a bunch of "WARNING ..." messages displayed as it started up but it doesn't seem to have run into anything critical. It's still running Sirius at the moment, I guess that normally takes a while?

I left this running overnight - it ended up taking over 7 hours on a PC with a fairly recent 12-core CPU, is that a typical amount of time?? This was using the MSV000079284 dataset from the platform. Is there a way for it to display some progress information while it's running?

**Comment by louwenjjr** [comment]
>It looks like when you run pip install in that particular form it doesn't actually copy the source files anywhere, it just inserts the directory into the PYTHONPATH. If I remove the "rm -rf" line then it imports that module without any trouble.

Okay, nice thanks!

>I left this running overnight - it ended up taking over 7 hours on a PC with a fairly recent 12-core CPU, is that a typical amount of time?? This was using the MSV000079284 dataset from the platform.

Unfortunately, yes. The calculations for the fragmentation trees in SIRIUS take a while. You can lower the --maxmz parameter so it runs for fewer spectra (only spectra with masses below that threshold), for example to 400. My guess it will then take half an hour or so for that data. Maybe we should adjust the default to 600 or so to not discourage people if it takes a while?

>Is there a way for it to display some progress information while it's running?

The whole sirius process should print a lot of output actually. Is this not the case for you?

**Comment by andrewramsay** [comment]
> Unfortunately, yes. The calculations for the fragmentation trees in SIRIUS take a while. You can lower the --maxmz parameter so it runs for fewer spectra (only spectra with masses below that threshold), for example to 400. My guess it will then take half an hour or so for that data. Maybe we should adjust the default to 600 or so to not discourage people if it takes a while?

I was just wondering if something had gone wrong because I expected it to take a similar amount of time to something like BiG-SCAPE! Does throwing more cores at it make a significant difference? 

Happy to go with whatever default you think makes sense, and it would probably be good to have something in the documentation of the run_canopus setting in the data/nplinker.toml file that explains if you set it to true then you'll need to be prepared to wait for a significant amount of time. 

> The whole sirius process should print a lot of output actually. Is this not the case for you?

I've deleted the Docker container already so I don't have the actual log output unfortunately, but what I remember seeing was an initial burst of many "INFO" and "WARNING" messages about various things but then it just stopped printing anything for at least 2-3 hours. I could see in htop that there were multiple CPU-intensive processes running in the background but there didn't seem to be any console output coming through. When I checked back this morning it had printed a lot more messages towards the end of its runtime and then the rest of the NPLinker loading process had completed as usual. Is it supposed to continue printing progress info at regular intervals throughout?

**Comment by louwenjjr** [comment]
> I was just wondering if something had gone wrong because I expected it to take a similar amount of time to something like BiG-SCAPE! Does throwing more cores at it make a significant difference?

Happy to go with whatever default you think makes sense, and it would probably be good to have something in the documentation of the run_canopus setting in the data/nplinker.toml file that explains if you set it to true then you'll need to be prepared to wait for a significant amount of time.

Yea throwing more cores at it helps! I'll have a think about the parameters and writing it down in the toml :)

>I've deleted the Docker container already so I don't have the actual log output unfortunately, but what I remember seeing was an initial burst of many "INFO" and "WARNING" messages about various things but then it just stopped printing anything for at least 2-3 hours. I could see in htop that there were multiple CPU-intensive processes running in the background but there didn't seem to be any console output coming through. When I checked back this morning it had printed a lot more messages towards the end of its runtime and then the rest of the NPLinker loading process had completed as usual. Is it supposed to continue printing progress info at regular intervals throughout?

Ah, right. So SIRIUS prints a massive amount of info/warnings for each spectrum in the mgf file when it loads them. Then the steps where it runs ZODIAC, CANOPUS, and the final step of compiling the results run without additional messages indeed which is slightly annoying. Is there anything we can do for that though?

**Comment by andrewramsay** [comment]
> Ah, right. So SIRIUS prints a massive amount of info/warnings for each spectrum in the mgf file when it loads them. Then the steps where it runs ZODIAC, CANOPUS, and the final step of compiling the results run without additional messages indeed which is slightly annoying. Is there anything we can do for that though?

Sounds like an ideal solution would involve updating the source code for Sirius etc so I guess probably not. Does the loglevel parameter make any difference to that behaviour? I can see in the "sirius -h" output it says:
 
> --log, --loglevel=<logLevel>
                            Set logging level of the Jobs SIRIUS will execute.
                              Valid values: SEVERE, WARNING, INFO, FINER, ALL
                              Default: WARNING

Maybe setting this to FINER or ALL would produce some output during those phases? Not sure the "Default: WARNING" part is accurate because I'm sure I saw INFO-level messages too. Anyway I can try this out tomorrow, I have some other CPU-intensive stuff running on my PC today that I can't interrupt.

**Comment by louwenjjr** [comment]
>Maybe setting this to FINER or ALL would produce some output during those phases? Not sure the "Default: WARNING" part is accurate because I'm sure I saw INFO-level messages too. Anyway I can try this out tomorrow, I have some other CPU-intensive stuff running on my PC today that I can't interrupt.

Thanks for checking, I will also look into this a bit.

**Comment by louwenjjr** [comment]
Seems that with --log INFO already enough messages are printed. It then at least prints that it is running zodiac and canopus. There are a lot of messages though.. But no easy way around that currently other then just writing all the log output from sirius to a file I think. So I think this is the best option.

**Comment by louwenjjr** [comment]
I updated the demo notebook with rosetta scoring! :)

**Comment by justinjjvanderhooft** [comment]
👍 😊

**Comment by andrewramsay** [comment]
> I updated the demo notebook with rosetta scoring! :)

I'd like to try running the notebook with my copy of the Crusemann dataset but I'll need to let it churn through the SIRIUS /Canopus process first, so it might be a while before I can actually do that. Although that adjustment to the --maxmz parameter should speed it up as you said!

I think things look good though, happy to go ahead and merge this after I've tried out the notebook.

**Comment by andrewramsay** [comment]
I was just thinking that Crusemann would be much more likely to produce some actual Rosetta results than the much smaller datasets I already have. But I guess it doesn't really matter too much, the code looks fine! I'll try it with a smaller one to save some time then.

**Comment by louwenjjr** [comment]
> I was just thinking that Crusemann would be much more likely to produce some actual Rosetta results than the much smaller datasets I already have. But I guess it doesn't really matter too much, the code looks fine! I'll try it with a smaller one to save some time then.

Ah yea I get your point. Within Crusemann I also only get ~30 GCFs with a rosetta link.

**Comment by andrewramsay** [comment]
I think I just came across another minor issue with the updated Dockerfile: the downloaded SIRIUS executable doesn't get added to the PATH. Adding it at the same time as BiG-SCAPE should fix it:

> ENV PATH="/app/conda/bin:/app/BiG-SCAPE:/app/sirius/bin:${PATH}"

**Comment by andrewramsay** [comment]
OK, the notebook runs fine for me and it finds plenty of links using NPClassScore. Although there are some warnings shown when loading:

```
22:00:37 [INFO] class_matches.py:44, Loaded MIBiG classes, and class matching tables
22:00:37 [INFO] chem_classes.py:107, Converting canopus output using canopus_treemap
6708 compounds in workspace 
Cannot find gnps_molecular_network_graphml file in the given directory
22:01:32 [WARNING] chem_classes.py:111, canopus_treemap failed with: 'Canopus' object has no attribute 'gnps'. Probably the MN version from GNPS is too old
22:01:32 [INFO] chem_classes.py:142, Attempting to read spectra classes directly from canopus_dir (canopus_summary.tsv)
22:01:32 [INFO] chem_classes.py:218, reading canopus results for spectra directly from C:\nplinker_data\pairedomics\extracted\MSV000079284\canopus\canopus_summary.tsv
22:01:32 [WARNING] chem_classes.py:361, no molnetenhancer input found in C:\nplinker_data\pairedomics\extracted\MSV000079284\molnetenhancer
```

Anything to worry about there or are they normal for some datasets?

A couple of other quick comments:

- I think the setup.py for canopus treemap.git needs updated to have `package_data={'': ['*.js','*.txt','*.csv', '*.json']},`. Without that pip doesn't appear to copy the `resources/npc_index.json` file along with the others and then that causes an error when it calls analyse_canopus from chem_classes.py
- I haven't read through the details of the NPClassScore method to know if this is a feasible thing to do, but is there any scope for caching results? The notebook is using all the GCFs in the dataset as input in a few different cells and it takes ~10s each call for the one I'm using since it recalculates each time. But that's very much a nice-to-have rather than need-to-have, we can go ahead and merge this without it!

**Comment by louwenjjr** [comment]
>22:00:37 [INFO] chem_classes.py:107, Converting canopus output using canopus_treemap
6708 compounds in workspace 
Cannot find gnps_molecular_network_graphml file in the given directory
22:01:32 [WARNING] chem_classes.py:111, canopus_treemap failed with: 'Canopus' object has no attribute 'gnps'. Probably the MN version from GNPS is too old

Yea, this is normal for this dataset. The canopus treemap is mainly not my own code and therefore only works on newer gnps datasets >=SNETS-V2. I added the canopus_treemap code to get NPC classes as these are not in the normal SIRIUS output yet, and to have some more insight into how CF and NPC classes are assigned within canopus as this is not clear at all to me. For older gnps outputs the canopus output is read directly (so only CF classes). I need to add a feature that the classes are also assigned to MFs if that happens, but I don't think that has priority now.

> 22:01:32 [WARNING] chem_classes.py:361, no molnetenhancer input found in C:\nplinker_data\pairedomics\extracted\MSV000079284\molnetenhancer

I thought it would be nice to message if there is no molnetenhancer results. However, most people will not actually include this I guess, so if you have another suggestion please say so.

> I think the setup.py for canopus treemap.git needs updated to have package_data={'': ['*.js','*.txt','*.csv', '*.json']},. Without that pip doesn't appear to copy the resources/npc_index.json file along with the others and then that causes an error when it calls analyse_canopus from chem_classes.py

Thanks for noticing, I will add it.

>I haven't read through the details of the NPClassScore method to know if this is a feasible thing to do, but is there any scope for caching results? The notebook is using all the GCFs in the dataset as input in a few different cells and it takes ~10s each call for the one I'm using since it recalculates each time.

Yes I wanted to get around to this! But just haven't yet. For this large dataset it doesn't take that long so I thought it would be okay for now.

>But that's very much a nice-to-have rather than need-to-have, we can go ahead and merge this without it!

That is great! Thanks for all your help :)

**Pull request merged**
