### PR TITLE
remove smiles prediction

### PR DESCRIPTION
**Pull request by CunliangGeng**
we decided on the community meeting to remove SMILES prediction.

### CODE REVIEW

**Comment by CunliangGeng** [comment]
* **#289** <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/289?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/NPLinker/nplinker/289?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by gcroci2 — COMMENTED** [review]
Did you receive an OK for removing smiles completely (including the ones for mibig BGC)?

If yes, then we need to remove them from other files as well (`src/nplinker/genomics/antismash/antismash_loader.py`, `src/nplinker/scoring/iokr/nplinker_iokr.py`, etc.)

**Comment by CunliangGeng** [comment]
yes, it's confirmed. I just removed that from BGC files. But I don't want to touch the iokr files, which should be changed in refactoring.

**Review by gcroci2 — APPROVED** [review]

**Comment by CunliangGeng** [comment]
### Merge activity

* **Dec 11, 4:01 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/289).
* **Dec 11, 4:02 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/NPLinker/nplinker/289).

**Pull request merged**
